### ISSUE TITLE
Is there a plan to add dotnet interactive into kaggle notebook

### ISSUE THREAD

**Issue by LittleLittleCloud** [Kaggle/docker-julia#10]
Hi Kaggle

Jupyter notebook has already support C# through dotnet interactive, here's a sample
> https://mybinder.org/v2/gh/dotnet/interactive/main?urlpath=lab

Just wondering if kaggle notebook supports that too

**Comment by rosbo** [comment]
Hi,

We don't support C# and have no plans currently to expand to languages beyond Python and R.

Julia is also not supported anymore on Kaggle notebooks.

Thank you
